version = "1"
root = "."
ignore = [
  "CHANGELOG.md",
  "README.md",
  "docs/dist",
]

[docs]
source = "docs/src"
output = "docs/dist"

[health]
ignore-unexplained = [
  "src/language_packs/*/test_fixtures.rs",
  "src/language_packs/*/test_fixtures/**",
  "src/render/html/*_templates.rs",
  "src/render/text/*_templates.rs",
]
