# @module SPECIAL.RELEASE_REVIEW.PIPELINE
# Facade over release-review context extraction and planning helpers.
# @fileimplements SPECIAL.RELEASE_REVIEW.PIPELINE
from __future__ import annotations

from release_review_context import (
    CHARS_PER_TOKEN,
    HUNK_RE,
    MAX_CONTEXT_CHARS,
    MAX_INPUT_CHARS,
    MAX_INPUT_TOKENS,
    NON_RUST_FULL_SCAN_LINES,
    NON_RUST_SNIPPET_PADDING,
    REVIEW_PATHS,
    RUST_ITEM_RE,
    build_file_contexts,
    changed_files_from_diff,
    chunk_line_ranges,
    command_exists,
    diff_text_for_paths,
    discover_latest_semver_tag,
    extend_with_attributes,
    extract_context_ranges,
    extract_top_level_rust_ranges,
    find_rust_item_range,
    full_scan_files,
    include_file,
    list_repo_text_files,
    list_review_files,
    matches_review_scope,
    merge_ranges,
    parse_changed_line_ranges,
    split_large_context,
    window_range,
)
from release_review_planning import (
    MAX_CONCURRENT_REVIEW_CHUNKS,
    PROJECT_REVIEW_RULES,
    REVIEW_PASSES,
    SCOPE_RULES,
    build_pass_chunks,
    build_prompt,
    build_review_passes,
    estimate_chars,
    pass_matches_file,
)

__all__ = [
    "CHARS_PER_TOKEN",
    "HUNK_RE",
    "MAX_CONCURRENT_REVIEW_CHUNKS",
    "MAX_CONTEXT_CHARS",
    "MAX_INPUT_CHARS",
    "MAX_INPUT_TOKENS",
    "NON_RUST_FULL_SCAN_LINES",
    "NON_RUST_SNIPPET_PADDING",
    "PROJECT_REVIEW_RULES",
    "REVIEW_PASSES",
    "REVIEW_PATHS",
    "RUST_ITEM_RE",
    "SCOPE_RULES",
    "build_file_contexts",
    "build_pass_chunks",
    "build_prompt",
    "build_review_passes",
    "changed_files_from_diff",
    "chunk_line_ranges",
    "command_exists",
    "diff_text_for_paths",
    "discover_latest_semver_tag",
    "estimate_chars",
    "extend_with_attributes",
    "extract_context_ranges",
    "extract_top_level_rust_ranges",
    "find_rust_item_range",
    "full_scan_files",
    "include_file",
    "list_repo_text_files",
    "list_review_files",
    "matches_review_scope",
    "merge_ranges",
    "parse_changed_line_ranges",
    "pass_matches_file",
    "split_large_context",
    "window_range",
]
